name: Daily Micro-Cap Data

on:
  schedule:
    # Weekdays 22:00 UTC (~6:00 PM ET during DST). Adjust as desired.
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch prices & history
        run: python scripts/fetch_prices.py
      - name: Daily analysis
        run: python scripts/analyze_portfolio.py --mode daily
      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          add: "outputs/."
          message: "chore: daily data & report [skip ci]"
