name: Weekend Deep Dive

on:
  schedule:
    # Saturdays 16:00 UTC (~12:00 PM ET during DST). Adjust as desired.
    - cron: "0 16 * * 6"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Refresh latest data
        run: python scripts/fetch_prices.py
      - name: Weekend analysis
        run: python scripts/analyze_portfolio.py --mode weekend
      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          add: "outputs/."
          message: "chore: weekend deep dive report [skip ci]"
